### ISSUE TITLE
I still get ExpiredTokenException: UnkownError

### ISSUE THREAD

**Issue by narayananramu** [scaleapi/mongodb-auth-aws-improved#1]
I get this error.
<img width="796" alt="Screenshot 2022-08-24 at 10 14 04 AM" src="https://user-images.githubusercontent.com/5837582/186330793-d192db9f-d4da-4712-954c-9f575bb3533f.png">
Here is my configuration.
<img width="824" alt="Screenshot 2022-08-24 at 10 12 32 AM" src="https://user-images.githubusercontent.com/5837582/186330623-957f0b9d-4939-4780-b007-97e801f35c43.png">
<img width="681" alt="Screenshot 2022-08-24 at 10 13 06 AM" src="https://user-images.githubusercontent.com/5837582/186330674-3ea85e49-7833-4119-92ca-1c0b25b98f0a.png">

**Comment by clhuang** [comment]
I suggest you use [fromTokenFile](https://www.npmjs.com/package/@aws-sdk/credential-providers#fromtokenfile) instead of fromWebToken, as it will automatically reload the contents of the web identity token file.

**Comment by narayananramu** [comment]
thanks, I have updated my code. I will re-open if the issue persists.
